# Generated by Django 4.2 on 2023-05-19 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('dimensions', models.CharField(blank=True, max_length=128)),
                ('materials', models.CharField(blank=True, max_length=256)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('available', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('art_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_gallery.artpiece')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('art_pieces', models.ManyToManyField(related_name='categories', through='art_gallery.Categorized', to='art_gallery.artpiece')),
            ],
        ),
        migrations.AddField(
            model_name='categorized',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_gallery.category'),
        ),
        migrations.CreateModel(
            name='ArtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large', models.ImageField(upload_to='')),
                ('display', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('art_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_gallery.artpiece')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art_gallery.category')),
            ],
        ),
    ]
