# Generated by Django 4.2.1 on 2023-05-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='artimage',
            name='category',
        ),
        migrations.AddField(
            model_name='artimage',
            name='featured',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='artimage',
            name='display',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artimage',
            name='large',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='available',
            field=models.BooleanField(null=True),
        ),
    ]
