# Generated by Django 4.2.1 on 2023-05-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery', '0002_alter_category_options_remove_artimage_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artimage',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='available',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
