# Generated by Django 4.2.1 on 2023-05-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery', '0003_alter_artimage_featured_alter_artpiece_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artimage',
            name='display',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails'),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
