# Generated by Django 4.2.1 on 2023-05-27 16:49

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery', '0004_alter_artimage_display_alter_artpiece_available_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('title'), name='unique_lower_title_category'),
        ),
    ]
